language: python
python:
  - "2.7"
before_install:
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
install:
  - sudo apt-get install
# coveralls.io
  - pip install python-coveralls requests[security]
# install mock
  - pip install mock
script: make tests COVERAGE="coverage run --include='bleachbit/*'"
after_success:
   - mv .coverage .coverage.travis
   - sudo pip install appveyor-artifacts
   - appveyor-artifacts -o az0 -n bleachbit -m download
   - coverage combine
   - coverage report
   - coveralls
