language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get -y install build-essential gcc python-dev pkg-config libglib2.0-dev python-gobject-2-dev"
  - "wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2"
  - "tar -jxf pygtk*"
  - "cd pygtk-2.24.0"
  - "./configure"
  - "make"
  - "sudo make install"
  - "cd .."
script: make tests
