build: off
version: 2.0.{build}

environment:
    PYTHON_HOME: 'C:/Python27'
    SZ_EXE   :   '"C:/Program Files/7-Zip/7z.exe"'
    make : 'C:/MinGW/bin/mingw32-make.exe'

init:
  - 'echo PYTHON_HOME=%PYTHON_HOME%'
  - '%PYTHON_HOME%/python.exe -V'
  - '%PYTHON_HOME%/Scripts/pip.exe --version'

install:
  - '%PYTHON_HOME%/Scripts/pip.exe install psutil'
  - '%PYTHON_HOME%/Scripts/pip.exe install pypiwin32'
  - '%PYTHON_HOME%/Scripts/pip.exe install winshell'
  - '%PYTHON_HOME%/Scripts/pip.exe install py2exe_py2'
  - ps: if (-not (Test-Path pygi-aio-3.18.2_rev11-setup_db3872aed9e1f378a14c941fe1c05f177a60fa8c.exe )) { Start-FileDownload "https://sourceforge.net/projects/pygobjectwin32/files/pygi-aio-3.18.2_rev11-setup_db3872aed9e1f378a14c941fe1c05f177a60fa8c.exe/download" }
  - 'pygi-aio-3.18.2_rev11-setup_db3872aed9e1f378a14c941fe1c05f177a60fa8c.exe C:\Python27 GTK Notify'
  - ps: if (-not (Test-Path upx394w.zip)) { Start-FileDownload "http://github.com/upx/upx/releases/download/v3.94/upx394w.zip" }
  - '%SZ_EXE% x upx394w.zip'
  - ps: if (-not (Test-Path gettext0.19.8.1-iconv1.14-static-32.zip)) { Start-FileDownload "http://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/gettext0.19.8.1-iconv1.14-static-32.zip" }
  - '%SZ_EXE% x gettext0.19.8.1-iconv1.14-static-32.zip -ogettext'
  - 'set PATH=%PATH%;%cd%\gettext\bin;C:\MinGW\bin;'
# Show version numbers of installed software.
  - 'msgunfmt -V'
  - 'strip.exe -V'
  - '"c:\Program Files (x86)\NSIS\makensis.exe" /version'

build_script:
  - '%make% -C po local'
  - '%PYTHON_HOME%/python.exe -m windows.setup_py2exe'
  - 'move windows\BleachBit*.exe .'
  - 'move windows\BleachBit*.zip .'
  - ps: Get-FileHash BleachBit-*

cache:
  - pygi-aio-3.18.2_rev11-setup_db3872aed9e1f378a14c941fe1c05f177a60fa8c.exe
  - upx394w.zip
  - gettext0.19.8.1-iconv1.14-static-32.zip

test_script:
# coveralls.io
  - '%PYTHON_HOME%/Scripts/pip.exe install python-coveralls requests[security]'
# shorten very long path because of error https://github.com/az0/bleachbit/issues/166
  - 'set PATH=c:\windows\system32;c:\windows;c:\windows\system32\wbem'
  - '%PYTHON_HOME%/Scripts/pip.exe install mock'
  - 'SET DESTRUCTIVE_TESTS=T'
  - '%PYTHON_HOME%/Scripts/coverage.exe run --include="bleachbit/*" -m unittest discover -v -p Test*.py'

artifacts:
  - path: BleachBit-*-setup.exe
    name: FullInstaller

  - path: BleachBit-*-setup-English.exe
    name: EnglishInstaller

  - path: BleachBit-*-portable.zip
    name: Portable

  - path: .coverage

deploy:
  - provider: S3
    access_key_id:
      secure: CrPvjz7Jvg4gwOHKxUsL0PPR4mqAjB2p15/pvFw3fCk=
    secret_access_key:
      secure: VoAH5pVyhmTK3/KRuV5WcgfkTR3k/M9QDt7UD6ewcwNfkUvMynwjAHnKCG4vR0Rx
    bucket: bleachbitci
    folder: dl/$(APPVEYOR_BUILD_VERSION)
    artifact:
    set-public: true
    reduced_redundancy: true
